mod content;
mod market_trading;
mod new_coin_convert;
mod risk_security;
mod system_config;
mod users_agents;
mod wallet_assets;

use crate::modules::admin::service::{admin_id_from_subject, load_market_feed_runtime};
use crate::{
    error::AppResult,
    modules::{
        admin::{
            application::{
                assign_admin_user_agent as assign_user_agent_use_case,
                create_admin_agent as create_agent_use_case,
                create_admin_agent_commission_rule as create_agent_commission_rule_use_case,
                create_admin_asset as create_asset_use_case,
                create_admin_convert_pair as create_convert_pair_use_case,
                create_admin_country as create_admin_country_use_case,
                create_admin_deposit_address_pool as create_deposit_address_pool_use_case,
                create_admin_deposit_address_pool_batch as create_deposit_address_pool_batch_use_case,
                create_admin_deposit_network_config as create_deposit_network_config_use_case,
                create_admin_market_strategy as create_market_strategy_use_case,
                create_admin_new_coin_project as create_new_coin_project_use_case,
                create_admin_news_item as create_admin_news_item_use_case,
                create_admin_risk_rule as create_risk_rule_use_case,
                create_admin_smtp_config as create_smtp_config_use_case,
                create_admin_trading_pair as create_trading_pair_use_case,
                create_admin_user as create_admin_user_use_case,
                delete_admin_asset as delete_asset_use_case,
                delete_admin_convert_pair as delete_convert_pair_use_case,
                detect_admin_market_strategy_gaps as detect_market_strategy_gaps_use_case,
                distribute_admin_new_coin as distribute_new_coin_use_case,
                execute_admin_market_strategy_recovery as execute_market_strategy_recovery_use_case,
                get_admin_agent as get_agent_use_case, get_admin_asset as get_asset_use_case,
                get_admin_convert_order as get_convert_order_use_case,
                get_admin_convert_pair as get_convert_pair_use_case,
                get_admin_dashboard as get_admin_dashboard_use_case,
                get_admin_deposit_address_pool as get_deposit_address_pool_use_case,
                get_admin_kyc_config as get_kyc_config_use_case,
                get_admin_kyc_submission as get_kyc_submission_use_case,
                get_admin_margin_liquidation as get_margin_liquidation_use_case,
                get_admin_market_feed_config as get_market_feed_config_use_case,
                get_admin_market_feed_status as get_market_feed_status_use_case,
                get_admin_market_strategy as get_market_strategy_use_case,
                get_admin_news_item as get_admin_news_item_use_case,
                get_admin_platform_brand as get_platform_brand_use_case,
                get_admin_security_policy as get_security_policy_use_case,
                get_admin_smtp_config as get_smtp_config_use_case,
                get_admin_trading_pair as get_trading_pair_use_case,
                get_admin_upload_config as get_upload_config_use_case,
                get_admin_user as get_admin_user_use_case,
                list_admin_agent_commission_rules as list_agent_commission_rules_use_case,
                list_admin_agent_commissions as list_agent_commissions_use_case,
                list_admin_agent_users as list_agent_users_use_case,
                list_admin_agents as list_agents_use_case,
                list_admin_assets as list_assets_use_case,
                list_admin_audit_logs as list_admin_audit_logs_use_case,
                list_admin_convert_orders as list_convert_orders_use_case,
                list_admin_convert_pairs as list_convert_pairs_use_case,
                list_admin_countries as list_admin_countries_use_case,
                list_admin_deposit_address_pool as list_deposit_address_pool_use_case,
                list_admin_deposit_network_configs as list_deposit_network_configs_use_case,
                list_admin_kyc_submissions as list_kyc_submissions_use_case,
                list_admin_margin_liquidations as list_margin_liquidations_use_case,
                list_admin_market_feed_credentials as list_market_feed_credentials_use_case,
                list_admin_market_strategies as list_market_strategies_use_case,
                list_admin_market_strategy_recovery_jobs as list_market_strategy_recovery_jobs_use_case,
                list_admin_new_coin_distributions as list_new_coin_distributions_use_case,
                list_admin_new_coin_distributions_for_project as list_new_coin_distributions_for_project_use_case,
                list_admin_new_coin_lock_positions as list_new_coin_lock_positions_use_case,
                list_admin_new_coin_projects as list_new_coin_projects_use_case,
                list_admin_new_coin_purchases as list_new_coin_purchases_use_case,
                list_admin_new_coin_subscriptions as list_new_coin_subscriptions_use_case,
                list_admin_new_coin_subscriptions_for_project as list_new_coin_subscriptions_for_project_use_case,
                list_admin_new_coin_unlocks as list_new_coin_unlocks_use_case,
                list_admin_news_items as list_admin_news_items_use_case,
                list_admin_risk_events as list_risk_events_use_case,
                list_admin_risk_rules as list_risk_rules_use_case,
                list_admin_smtp_configs as list_smtp_configs_use_case,
                list_admin_trading_pairs as list_trading_pairs_use_case,
                list_admin_users as list_admin_users_use_case,
                list_admin_wallet_accounts as list_wallet_accounts_use_case,
                list_admin_wallet_ledger as list_wallet_ledger_use_case, mysql_pool,
                preview_admin_market_strategy_recovery as preview_market_strategy_recovery_use_case,
                recharge_admin_user_wallet as recharge_admin_user_wallet_use_case,
                reclaim_admin_deposit_address_pool as reclaim_deposit_address_pool_use_case,
                reload_admin_market_feed_config as reload_market_feed_config_use_case,
                reset_admin_agent_password as reset_agent_password_use_case,
                reset_admin_user_two_factor as reset_admin_user_two_factor_use_case,
                review_admin_kyc_submission as review_kyc_submission_use_case,
                save_admin_kyc_config as save_kyc_config_use_case,
                save_admin_market_feed_config as save_market_feed_config_use_case,
                save_admin_platform_brand as save_platform_brand_use_case,
                save_admin_smtp_config as save_smtp_config_use_case,
                save_admin_smtp_delivery_settings as save_smtp_delivery_settings_use_case,
                save_admin_upload_config as save_upload_config_use_case,
                send_admin_smtp_test as send_smtp_test_use_case,
                update_admin_agent_commission_rule as update_agent_commission_rule_use_case,
                update_admin_agent_commission_status as update_agent_commission_status_use_case,
                update_admin_agent_commission_statuses as update_agent_commission_statuses_use_case,
                update_admin_agent_status as update_agent_status_use_case,
                update_admin_asset as update_asset_use_case,
                update_admin_convert_pair as update_convert_pair_use_case,
                update_admin_country as update_admin_country_use_case,
                update_admin_country_status as update_admin_country_status_use_case,
                update_admin_deposit_address_pool as update_deposit_address_pool_use_case,
                update_admin_deposit_network_config as update_deposit_network_config_use_case,
                update_admin_market_strategy as update_market_strategy_use_case,
                update_admin_market_strategy_status as update_market_strategy_status_use_case,
                update_admin_new_coin_lifecycle as update_new_coin_lifecycle_use_case,
                update_admin_new_coin_post_listing_purchase as update_new_coin_post_listing_purchase_use_case,
                update_admin_new_coin_unlock_fee_rule as update_new_coin_unlock_fee_rule_use_case,
                update_admin_new_coin_unlock_rule as update_new_coin_unlock_rule_use_case,
                update_admin_news_item as update_admin_news_item_use_case,
                update_admin_news_status as update_admin_news_status_use_case,
                update_admin_risk_rule_status as update_risk_rule_status_use_case,
                update_admin_security_policy as update_security_policy_use_case,
                update_admin_smtp_config as update_smtp_config_use_case,
                update_admin_trading_pair as update_trading_pair_use_case,
                update_admin_trading_pair_status as update_trading_pair_status_use_case,
                update_admin_user_status as update_admin_user_status_use_case,
                upload_admin_image as upload_image_use_case,
                upsert_admin_market_feed_credential as upsert_market_feed_credential_use_case,
                upsert_admin_new_coin_convert_rule as upsert_new_coin_convert_rule_use_case,
            },
            presentation::{
                AdminAgentCommissionBatchStatusResponse, AdminAgentCommissionQuery,
                AdminAgentCommissionResponse, AdminAgentCommissionRuleQuery,
                AdminAgentCommissionRuleResponse, AdminAgentCommissionRulesResponse,
                AdminAgentCommissionsResponse, AdminAgentPasswordResetResponse, AdminAgentQuery,
                AdminAgentResponse, AdminAgentUsersQuery, AdminAgentUsersResponse,
                AdminAgentsResponse, AdminAssetQuery, AdminAssetResponse, AdminAssetsResponse,
                AdminAuditLogsQuery, AdminAuditLogsResponse, AdminConvertOrdersQuery,
                AdminConvertPairQuery, AdminCountriesQuery, AdminCountriesResponse,
                AdminCountryResponse, AdminDashboardResponse, AdminDepositAddressPoolBatchResponse,
                AdminDepositAddressPoolQuery, AdminDepositAddressPoolResponse,
                AdminDepositAddressPoolResponseList, AdminDepositNetworkConfigQuery,
                AdminDepositNetworkConfigResponse, AdminDepositNetworkConfigResponseList,
                AdminKycSubmissionQuery, AdminMarginLiquidationQuery,
                AdminMarginLiquidationResponse, AdminMarginLiquidationsResponse,
                AdminMarketStrategiesResponse, AdminMarketStrategyDetailResponse,
                AdminMarketStrategyQuery, AdminMarketStrategyResponse, AdminNewCoinFlatListQuery,
                AdminNewCoinLockPositionQuery, AdminNewCoinProjectQuery, AdminNewCoinPurchaseQuery,
                AdminNewCoinScopedListQuery, AdminNewCoinUnlockQuery, AdminNewsItemResponse,
                AdminNewsItemsResponse, AdminNewsQuery, AdminRiskEventQuery, AdminRiskRuleQuery,
                AdminTradingPairQuery, AdminTradingPairResponse, AdminTradingPairsResponse,
                AdminUserQuery, AdminUserRechargeRequest, AdminUserRechargeResponse,
                AdminUserReferralResponse, AdminUserResponse, AdminUserTwoFactorResetResponse,
                AdminUsersResponse, AdminWalletAccountQuery, AdminWalletAccountsResponse,
                AdminWalletLedgerQuery, AdminWalletLedgerResponseList, AssignUserAgentRequest,
                BatchUpdateAgentCommissionStatusRequest, ConvertOrderResponse,
                ConvertOrdersResponse, ConvertPairResponse, ConvertPairsResponse,
                CreateAdminCountryRequest, CreateAdminNewsItemRequest, CreateAdminUserRequest,
                CreateAgentCommissionRuleRequest, CreateAgentRequest, CreateAssetRequest,
                CreateConvertPairRequest, CreateDepositAddressPoolBatchRequest,
                CreateDepositAddressPoolRequest, CreateDepositNetworkConfigRequest,
                CreateMarketStrategyRequest, CreateNewCoinProjectRequest, CreateRiskRuleRequest,
                CreateTradingPairRequest, DeleteAssetRequest, DeleteConvertPairRequest,
                DistributeNewCoinRequest, ExecuteMarketStrategyRecoveryRequest,
                MarketFeedConfigResponse, MarketFeedStatusResponse, MarketSourceCredentialResponse,
                MarketSourceCredentialsResponse, MarketStrategyGapQuery,
                MarketStrategyGapsResponse, MarketStrategyRecoveryJobResponse,
                MarketStrategyRecoveryJobsQuery, MarketStrategyRecoveryJobsResponse,
                MarketStrategyRecoveryPreviewResponse, NewCoinConvertRuleResponse,
                NewCoinDistributionResponse, NewCoinDistributionsResponse,
                NewCoinLockPositionsResponse, NewCoinProjectResponse, NewCoinProjectsResponse,
                NewCoinPurchasesResponse, NewCoinSubscriptionsResponse, NewCoinUnlocksResponse,
                PreviewMarketStrategyRecoveryRequest, ReclaimDepositAddressPoolRequest,
                ReloadMarketFeedRequest, ReloadMarketFeedResponse, ResetAgentPasswordRequest,
                ResetUserTwoFactorRequest, RiskEventsResponse, RiskRuleResponse, RiskRulesResponse,
                SaveMarketFeedConfigRequest, SaveSmtpConfigRequest,
                SaveSmtpDeliverySettingsRequest, SaveUploadConfigRequest, SendSmtpTestRequest,
                SendSmtpTestResponse, SmtpConfigListResponse, SmtpConfigResponse,
                SmtpDeliverySettingsResponse, UpdateAdminCountryRequest,
                UpdateAdminCountryStatusRequest, UpdateAdminNewsItemRequest,
                UpdateAdminNewsStatusRequest, UpdateAgentCommissionRuleRequest,
                UpdateAgentCommissionStatusRequest, UpdateAgentStatusRequest, UpdateAssetRequest,
                UpdateConvertPairRequest, UpdateDepositAddressPoolRequest,
                UpdateDepositNetworkConfigRequest, UpdateMarketStrategyRequest,
                UpdateMarketStrategyStatusRequest, UpdateNewCoinLifecycleRequest,
                UpdateNewCoinPostListingPurchaseRequest, UpdateNewCoinUnlockFeeRuleRequest,
                UpdateNewCoinUnlockRuleRequest, UpdateRiskRuleStatusRequest,
                UpdateSecurityPolicyRequest, UpdateTradingPairRequest,
                UpdateTradingPairStatusRequest, UpdateUserStatusRequest, UploadConfigResponse,
                UploadImageResponse, UpsertMarketSourceCredentialRequest,
                UpsertNewCoinConvertRuleRequest, multipart_file_input,
            },
            service::MAX_UPLOAD_BODY_SIZE_BYTES,
        },
        auth::AdminAuth,
        kyc::{
            KycConfigResponse, KycSubmissionResponse, KycSubmissionsResponse,
            ReviewKycSubmissionRequest, SaveKycConfigRequest,
        },
        platform::{PlatformBrandResponse, SavePlatformBrandRequest},
        security::UserSecurityPolicy,
    },
    state::AppState,
};
use axum::{
    Json, Router,
    extract::{DefaultBodyLimit, Multipart, Path, Query, State},
    http::StatusCode,
    routing::{get, patch, post},
};

/// 构建完整 Admin API 路由的兼容 façade。
///
/// # 传输合同
/// - 每个实际入口仍由原 handler 的 `AdminAuth` 提取器完成鉴权，并使用完全相同的
///   URI、HTTP 方法、Path/Query/JSON/Multipart DTO 与响应类型。
/// - 子路由只执行输入解析、管理员 subject 到审计编号的转换、运行态依赖转发和统一错误传播；
///   SQL、事务、风险策略及 provider I/O 仍由 application/service 边界承担。
/// - 资源域拆分只改变 Rust 模块组织；独立 OpenAPI 目录中的注册路径与 schema 引用不经此处重写。
/// - 任一提取或应用错误继续通过既有 `AppError` 映射返回，避免改变状态码和错误载荷。
pub fn routes() -> Router<AppState> {
    Router::new()
        .merge(system_config::routes())
        .merge(content::routes())
        .merge(users_agents::routes())
        .merge(wallet_assets::routes())
        .merge(risk_security::routes())
        .merge(market_trading::routes())
        .merge(new_coin_convert::routes())
}

#[cfg(test)]
#[path = "../../../tests/unit_src/src_modules_admin_routes_tests.rs"]
mod tests;
