CREATE TABLE new_coin_projects (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    asset_id BIGINT UNSIGNED NOT NULL UNIQUE,
    symbol VARCHAR(64) NOT NULL UNIQUE,
    lifecycle_status VARCHAR(32) NOT NULL DEFAULT 'preheat',
    total_supply DECIMAL(38,18) NOT NULL,
    issue_price DECIMAL(38,18) NOT NULL,
    listed_at TIMESTAMP(6) NULL,
    unlock_type VARCHAR(32) NOT NULL,
    fixed_unlock_at TIMESTAMP(6) NULL,
    relative_unlock_seconds BIGINT UNSIGNED NULL,
    unlock_fee_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    unlock_fee_rate DECIMAL(18,8) NULL,
    unlock_fee_basis VARCHAR(32) NULL,
    unlock_fee_asset BIGINT UNSIGNED NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX idx_new_coin_projects_lifecycle (lifecycle_status, status),
    CONSTRAINT fk_new_coin_projects_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT fk_new_coin_projects_fee_asset FOREIGN KEY (unlock_fee_asset) REFERENCES assets(id),
    CONSTRAINT chk_new_coin_projects_supply CHECK (total_supply > 0),
    CONSTRAINT chk_new_coin_projects_issue_price CHECK (issue_price >= 0)
);

CREATE TABLE new_coin_subscriptions (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    quote_asset BIGINT UNSIGNED NOT NULL,
    quote_amount DECIMAL(38,18) NOT NULL,
    requested_quantity DECIMAL(38,18) NOT NULL,
    allocated_quantity DECIMAL(38,18) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX idx_new_coin_subscriptions_project_user (project_id, user_id),
    INDEX idx_new_coin_subscriptions_user_time (user_id, created_at),
    CONSTRAINT fk_new_coin_subscriptions_project FOREIGN KEY (project_id) REFERENCES new_coin_projects(id),
    CONSTRAINT fk_new_coin_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_new_coin_subscriptions_quote_asset FOREIGN KEY (quote_asset) REFERENCES assets(id),
    CONSTRAINT chk_new_coin_subscriptions_amounts CHECK (quote_amount > 0 AND requested_quantity > 0 AND allocated_quantity >= 0)
);

CREATE TABLE new_coin_distributions (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    subscription_id BIGINT UNSIGNED NULL,
    asset_id BIGINT UNSIGNED NOT NULL,
    quantity DECIMAL(38,18) NOT NULL,
    lock_position_id BIGINT UNSIGNED NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX idx_new_coin_distributions_project_user (project_id, user_id),
    INDEX idx_new_coin_distributions_status (status, created_at),
    CONSTRAINT fk_new_coin_distributions_project FOREIGN KEY (project_id) REFERENCES new_coin_projects(id),
    CONSTRAINT fk_new_coin_distributions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_new_coin_distributions_subscription FOREIGN KEY (subscription_id) REFERENCES new_coin_subscriptions(id),
    CONSTRAINT fk_new_coin_distributions_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT fk_new_coin_distributions_lock_position FOREIGN KEY (lock_position_id) REFERENCES asset_lock_positions(id),
    CONSTRAINT chk_new_coin_distributions_quantity CHECK (quantity > 0)
);

CREATE TABLE new_coin_purchase_orders (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    pair_id BIGINT UNSIGNED NOT NULL,
    base_asset BIGINT UNSIGNED NOT NULL,
    quote_asset BIGINT UNSIGNED NOT NULL,
    price DECIMAL(38,18) NOT NULL,
    quantity DECIMAL(38,18) NOT NULL,
    quote_amount DECIMAL(38,18) NOT NULL,
    lock_position_id BIGINT UNSIGNED NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX idx_new_coin_purchase_orders_project_user (project_id, user_id),
    INDEX idx_new_coin_purchase_orders_pair_time (pair_id, created_at),
    CONSTRAINT fk_new_coin_purchase_orders_project FOREIGN KEY (project_id) REFERENCES new_coin_projects(id),
    CONSTRAINT fk_new_coin_purchase_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_new_coin_purchase_orders_pair FOREIGN KEY (pair_id) REFERENCES trading_pairs(id),
    CONSTRAINT fk_new_coin_purchase_orders_base_asset FOREIGN KEY (base_asset) REFERENCES assets(id),
    CONSTRAINT fk_new_coin_purchase_orders_quote_asset FOREIGN KEY (quote_asset) REFERENCES assets(id),
    CONSTRAINT fk_new_coin_purchase_orders_lock_position FOREIGN KEY (lock_position_id) REFERENCES asset_lock_positions(id),
    CONSTRAINT chk_new_coin_purchase_orders_amounts CHECK (price >= 0 AND quantity > 0 AND quote_amount >= 0)
);

CREATE TABLE new_coin_lifecycle_events (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload_json JSON NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    INDEX idx_new_coin_lifecycle_events_project_time (project_id, created_at),
    CONSTRAINT fk_new_coin_lifecycle_events_project FOREIGN KEY (project_id) REFERENCES new_coin_projects(id),
    CONSTRAINT fk_new_coin_lifecycle_events_admin FOREIGN KEY (created_by) REFERENCES admin_users(id)
);
