CREATE TABLE seconds_contract_products (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    pair_id BIGINT UNSIGNED NOT NULL,
    stake_asset BIGINT UNSIGNED NOT NULL,
    duration_seconds INT UNSIGNED NOT NULL,
    payout_rate DECIMAL(18,8) NOT NULL,
    min_stake DECIMAL(38,18) NOT NULL,
    max_stake DECIMAL(38,18) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX idx_seconds_contract_products_status (status),
    INDEX idx_seconds_contract_products_pair (pair_id),
    CONSTRAINT fk_seconds_contract_products_pair FOREIGN KEY (pair_id) REFERENCES trading_pairs(id),
    CONSTRAINT fk_seconds_contract_products_stake_asset FOREIGN KEY (stake_asset) REFERENCES assets(id),
    CONSTRAINT chk_seconds_contract_products_duration CHECK (duration_seconds > 0),
    CONSTRAINT chk_seconds_contract_products_stake CHECK (min_stake > 0 AND (max_stake IS NULL OR max_stake >= min_stake)),
    CONSTRAINT chk_seconds_contract_products_payout CHECK (payout_rate >= 0)
);

CREATE TABLE seconds_contract_orders (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    pair_id BIGINT UNSIGNED NOT NULL,
    stake_asset BIGINT UNSIGNED NOT NULL,
    direction VARCHAR(16) NOT NULL,
    stake_amount DECIMAL(38,18) NOT NULL,
    payout_rate DECIMAL(18,8) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'opened',
    result VARCHAR(16) NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    opened_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    expires_at TIMESTAMP(6) NOT NULL,
    settled_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_seconds_contract_orders_user_idempotency (user_id, idempotency_key),
    INDEX idx_seconds_contract_orders_user_time (user_id, created_at),
    INDEX idx_seconds_contract_orders_product_status (product_id, status),
    CONSTRAINT fk_seconds_contract_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_seconds_contract_orders_product FOREIGN KEY (product_id) REFERENCES seconds_contract_products(id),
    CONSTRAINT fk_seconds_contract_orders_pair FOREIGN KEY (pair_id) REFERENCES trading_pairs(id),
    CONSTRAINT fk_seconds_contract_orders_stake_asset FOREIGN KEY (stake_asset) REFERENCES assets(id),
    CONSTRAINT chk_seconds_contract_orders_stake CHECK (stake_amount > 0)
);
