CREATE TABLE margin_products (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    pair_id BIGINT UNSIGNED NOT NULL,
    margin_asset BIGINT UNSIGNED NOT NULL,
    max_leverage DECIMAL(18,8) NOT NULL,
    min_margin DECIMAL(38,18) NOT NULL,
    max_margin DECIMAL(38,18) NULL,
    maintenance_margin_rate DECIMAL(18,8) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX idx_margin_products_status (status),
    INDEX idx_margin_products_pair (pair_id),
    CONSTRAINT fk_margin_products_pair FOREIGN KEY (pair_id) REFERENCES trading_pairs(id),
    CONSTRAINT fk_margin_products_margin_asset FOREIGN KEY (margin_asset) REFERENCES assets(id),
    CONSTRAINT chk_margin_products_leverage CHECK (max_leverage > 1),
    CONSTRAINT chk_margin_products_margin CHECK (min_margin > 0 AND (max_margin IS NULL OR max_margin >= min_margin)),
    CONSTRAINT chk_margin_products_maintenance CHECK (maintenance_margin_rate >= 0)
);

CREATE TABLE margin_positions (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    pair_id BIGINT UNSIGNED NOT NULL,
    margin_asset BIGINT UNSIGNED NOT NULL,
    direction VARCHAR(16) NOT NULL,
    margin_amount DECIMAL(38,18) NOT NULL,
    leverage DECIMAL(18,8) NOT NULL,
    notional_amount DECIMAL(38,18) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'opened',
    idempotency_key VARCHAR(255) NOT NULL,
    opened_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    closed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_margin_positions_user_idempotency (user_id, idempotency_key),
    INDEX idx_margin_positions_user_time (user_id, created_at),
    INDEX idx_margin_positions_product_status (product_id, status),
    CONSTRAINT fk_margin_positions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_margin_positions_product FOREIGN KEY (product_id) REFERENCES margin_products(id),
    CONSTRAINT fk_margin_positions_pair FOREIGN KEY (pair_id) REFERENCES trading_pairs(id),
    CONSTRAINT fk_margin_positions_margin_asset FOREIGN KEY (margin_asset) REFERENCES assets(id),
    CONSTRAINT chk_margin_positions_direction CHECK (direction IN ('long', 'short')),
    CONSTRAINT chk_margin_positions_margin CHECK (margin_amount > 0),
    CONSTRAINT chk_margin_positions_leverage CHECK (leverage > 0),
    CONSTRAINT chk_margin_positions_notional CHECK (notional_amount > 0)
);
