CREATE TABLE earn_products (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    asset_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(128) NOT NULL,
    term_days INT UNSIGNED NOT NULL,
    apr_rate DECIMAL(18,8) NOT NULL,
    min_subscribe DECIMAL(38,18) NOT NULL,
    max_subscribe DECIMAL(38,18) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX idx_earn_products_status (status),
    INDEX idx_earn_products_asset (asset_id),
    CONSTRAINT fk_earn_products_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT chk_earn_products_term CHECK (term_days > 0),
    CONSTRAINT chk_earn_products_apr CHECK (apr_rate >= 0),
    CONSTRAINT chk_earn_products_amount CHECK (min_subscribe > 0 AND (max_subscribe IS NULL OR max_subscribe >= min_subscribe))
);

CREATE TABLE earn_subscriptions (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    asset_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(38,18) NOT NULL,
    apr_rate DECIMAL(18,8) NOT NULL,
    term_days INT UNSIGNED NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'subscribed',
    idempotency_key VARCHAR(255) NOT NULL,
    subscribed_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    matures_at TIMESTAMP(6) NOT NULL,
    redeemed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_earn_subscriptions_user_idempotency (user_id, idempotency_key),
    INDEX idx_earn_subscriptions_user_time (user_id, created_at),
    INDEX idx_earn_subscriptions_product_status (product_id, status),
    CONSTRAINT fk_earn_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_earn_subscriptions_product FOREIGN KEY (product_id) REFERENCES earn_products(id),
    CONSTRAINT fk_earn_subscriptions_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT chk_earn_subscriptions_amount CHECK (amount > 0),
    CONSTRAINT chk_earn_subscriptions_term CHECK (term_days > 0),
    CONSTRAINT chk_earn_subscriptions_apr CHECK (apr_rate >= 0)
);
