CREATE TABLE margin_liquidation_records (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    position_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    pair_id BIGINT UNSIGNED NOT NULL,
    margin_asset BIGINT UNSIGNED NOT NULL,
    direction VARCHAR(16) NOT NULL,
    margin_amount DECIMAL(38,18) NOT NULL,
    notional_amount DECIMAL(38,18) NOT NULL,
    entry_price DECIMAL(38,18) NOT NULL,
    mark_price DECIMAL(38,18) NOT NULL,
    maintenance_margin_rate DECIMAL(18,8) NOT NULL,
    equity DECIMAL(38,18) NOT NULL,
    maintenance_margin DECIMAL(38,18) NOT NULL,
    realized_pnl DECIMAL(38,18) NOT NULL,
    payout_amount DECIMAL(38,18) NOT NULL,
    reason VARCHAR(64) NOT NULL,
    liquidated_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_margin_liquidation_records_position (position_id),
    INDEX idx_margin_liquidation_records_user_time (user_id, liquidated_at),
    INDEX idx_margin_liquidation_records_pair_time (pair_id, liquidated_at),
    CONSTRAINT fk_margin_liquidation_records_position FOREIGN KEY (position_id) REFERENCES margin_positions(id),
    CONSTRAINT fk_margin_liquidation_records_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_margin_liquidation_records_product FOREIGN KEY (product_id) REFERENCES margin_products(id),
    CONSTRAINT fk_margin_liquidation_records_pair FOREIGN KEY (pair_id) REFERENCES trading_pairs(id),
    CONSTRAINT fk_margin_liquidation_records_margin_asset FOREIGN KEY (margin_asset) REFERENCES assets(id),
    CONSTRAINT chk_margin_liquidation_records_direction CHECK (direction IN ('long', 'short')),
    CONSTRAINT chk_margin_liquidation_records_margin CHECK (margin_amount > 0),
    CONSTRAINT chk_margin_liquidation_records_notional CHECK (notional_amount > 0),
    CONSTRAINT chk_margin_liquidation_records_prices CHECK (entry_price > 0 AND mark_price > 0),
    CONSTRAINT chk_margin_liquidation_records_maintenance_rate CHECK (maintenance_margin_rate >= 0),
    CONSTRAINT chk_margin_liquidation_records_payout CHECK (payout_amount >= 0)
);
