-- Seed common ISO 3166-1 alpha-2 country/region codes for registration, KYC and news country selectors.
-- Existing country_configs rows keep their custom locale, registration, status and sort settings.
INSERT IGNORE INTO country_configs
    (country_code, country_name, default_locale, supported_locales, registration_enabled, status, sort_order)
VALUES
    ('AD', 'Andorra', 'en', JSON_ARRAY('en'), TRUE, 'active', 1000),
    ('AE', 'United Arab Emirates', 'en', JSON_ARRAY('en'), TRUE, 'active', 1001),
    ('AF', 'Afghanistan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1002),
    ('AG', 'Antigua and Barbuda', 'en', JSON_ARRAY('en'), TRUE, 'active', 1003),
    ('AI', 'Anguilla', 'en', JSON_ARRAY('en'), TRUE, 'active', 1004),
    ('AL', 'Albania', 'en', JSON_ARRAY('en'), TRUE, 'active', 1005),
    ('AM', 'Armenia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1006),
    ('AO', 'Angola', 'en', JSON_ARRAY('en'), TRUE, 'active', 1007),
    ('AQ', 'Antarctica', 'en', JSON_ARRAY('en'), TRUE, 'active', 1008),
    ('AR', 'Argentina', 'en', JSON_ARRAY('en'), TRUE, 'active', 1009),
    ('AS', 'American Samoa', 'en', JSON_ARRAY('en'), TRUE, 'active', 1010),
    ('AT', 'Austria', 'en', JSON_ARRAY('en'), TRUE, 'active', 1011),
    ('AU', 'Australia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1012),
    ('AW', 'Aruba', 'en', JSON_ARRAY('en'), TRUE, 'active', 1013),
    ('AX', 'Aland Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1014),
    ('AZ', 'Azerbaijan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1015),
    ('BA', 'Bosnia and Herzegovina', 'en', JSON_ARRAY('en'), TRUE, 'active', 1016),
    ('BB', 'Barbados', 'en', JSON_ARRAY('en'), TRUE, 'active', 1017),
    ('BD', 'Bangladesh', 'en', JSON_ARRAY('en'), TRUE, 'active', 1018),
    ('BE', 'Belgium', 'en', JSON_ARRAY('en'), TRUE, 'active', 1019),
    ('BF', 'Burkina Faso', 'en', JSON_ARRAY('en'), TRUE, 'active', 1020),
    ('BG', 'Bulgaria', 'en', JSON_ARRAY('en'), TRUE, 'active', 1021),
    ('BH', 'Bahrain', 'en', JSON_ARRAY('en'), TRUE, 'active', 1022),
    ('BI', 'Burundi', 'en', JSON_ARRAY('en'), TRUE, 'active', 1023),
    ('BJ', 'Benin', 'en', JSON_ARRAY('en'), TRUE, 'active', 1024),
    ('BL', 'Saint Barthelemy', 'en', JSON_ARRAY('en'), TRUE, 'active', 1025),
    ('BM', 'Bermuda', 'en', JSON_ARRAY('en'), TRUE, 'active', 1026),
    ('BN', 'Brunei Darussalam', 'en', JSON_ARRAY('en'), TRUE, 'active', 1027),
    ('BO', 'Bolivia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1028),
    ('BQ', 'Bonaire, Sint Eustatius and Saba', 'en', JSON_ARRAY('en'), TRUE, 'active', 1029),
    ('BR', 'Brazil', 'en', JSON_ARRAY('en'), TRUE, 'active', 1030),
    ('BS', 'Bahamas', 'en', JSON_ARRAY('en'), TRUE, 'active', 1031),
    ('BT', 'Bhutan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1032),
    ('BV', 'Bouvet Island', 'en', JSON_ARRAY('en'), TRUE, 'active', 1033),
    ('BW', 'Botswana', 'en', JSON_ARRAY('en'), TRUE, 'active', 1034),
    ('BY', 'Belarus', 'en', JSON_ARRAY('en'), TRUE, 'active', 1035),
    ('BZ', 'Belize', 'en', JSON_ARRAY('en'), TRUE, 'active', 1036),
    ('CA', 'Canada', 'en', JSON_ARRAY('en'), TRUE, 'active', 1037),
    ('CC', 'Cocos Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1038),
    ('CD', 'Congo, Democratic Republic of the', 'en', JSON_ARRAY('en'), TRUE, 'active', 1039),
    ('CF', 'Central African Republic', 'en', JSON_ARRAY('en'), TRUE, 'active', 1040),
    ('CG', 'Congo', 'en', JSON_ARRAY('en'), TRUE, 'active', 1041),
    ('CH', 'Switzerland', 'en', JSON_ARRAY('en'), TRUE, 'active', 1042),
    ('CI', 'Cote d''Ivoire', 'en', JSON_ARRAY('en'), TRUE, 'active', 1043),
    ('CK', 'Cook Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1044),
    ('CL', 'Chile', 'en', JSON_ARRAY('en'), TRUE, 'active', 1045),
    ('CM', 'Cameroon', 'en', JSON_ARRAY('en'), TRUE, 'active', 1046),
    ('CN', 'China', 'en', JSON_ARRAY('en'), TRUE, 'active', 1047),
    ('CO', 'Colombia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1048),
    ('CR', 'Costa Rica', 'en', JSON_ARRAY('en'), TRUE, 'active', 1049),
    ('CU', 'Cuba', 'en', JSON_ARRAY('en'), TRUE, 'active', 1050),
    ('CV', 'Cabo Verde', 'en', JSON_ARRAY('en'), TRUE, 'active', 1051),
    ('CW', 'Curacao', 'en', JSON_ARRAY('en'), TRUE, 'active', 1052),
    ('CX', 'Christmas Island', 'en', JSON_ARRAY('en'), TRUE, 'active', 1053),
    ('CY', 'Cyprus', 'en', JSON_ARRAY('en'), TRUE, 'active', 1054),
    ('CZ', 'Czechia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1055),
    ('DE', 'Germany', 'en', JSON_ARRAY('en'), TRUE, 'active', 1056),
    ('DJ', 'Djibouti', 'en', JSON_ARRAY('en'), TRUE, 'active', 1057),
    ('DK', 'Denmark', 'en', JSON_ARRAY('en'), TRUE, 'active', 1058),
    ('DM', 'Dominica', 'en', JSON_ARRAY('en'), TRUE, 'active', 1059),
    ('DO', 'Dominican Republic', 'en', JSON_ARRAY('en'), TRUE, 'active', 1060),
    ('DZ', 'Algeria', 'en', JSON_ARRAY('en'), TRUE, 'active', 1061),
    ('EC', 'Ecuador', 'en', JSON_ARRAY('en'), TRUE, 'active', 1062),
    ('EE', 'Estonia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1063),
    ('EG', 'Egypt', 'en', JSON_ARRAY('en'), TRUE, 'active', 1064),
    ('EH', 'Western Sahara', 'en', JSON_ARRAY('en'), TRUE, 'active', 1065),
    ('ER', 'Eritrea', 'en', JSON_ARRAY('en'), TRUE, 'active', 1066),
    ('ES', 'Spain', 'en', JSON_ARRAY('en'), TRUE, 'active', 1067),
    ('ET', 'Ethiopia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1068),
    ('FI', 'Finland', 'en', JSON_ARRAY('en'), TRUE, 'active', 1069),
    ('FJ', 'Fiji', 'en', JSON_ARRAY('en'), TRUE, 'active', 1070),
    ('FK', 'Falkland Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1071),
    ('FM', 'Micronesia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1072),
    ('FO', 'Faroe Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1073),
    ('FR', 'France', 'en', JSON_ARRAY('en'), TRUE, 'active', 1074),
    ('GA', 'Gabon', 'en', JSON_ARRAY('en'), TRUE, 'active', 1075),
    ('GB', 'United Kingdom', 'en', JSON_ARRAY('en'), TRUE, 'active', 1076),
    ('GD', 'Grenada', 'en', JSON_ARRAY('en'), TRUE, 'active', 1077),
    ('GE', 'Georgia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1078),
    ('GF', 'French Guiana', 'en', JSON_ARRAY('en'), TRUE, 'active', 1079),
    ('GG', 'Guernsey', 'en', JSON_ARRAY('en'), TRUE, 'active', 1080),
    ('GH', 'Ghana', 'en', JSON_ARRAY('en'), TRUE, 'active', 1081),
    ('GI', 'Gibraltar', 'en', JSON_ARRAY('en'), TRUE, 'active', 1082),
    ('GL', 'Greenland', 'en', JSON_ARRAY('en'), TRUE, 'active', 1083),
    ('GM', 'Gambia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1084),
    ('GN', 'Guinea', 'en', JSON_ARRAY('en'), TRUE, 'active', 1085),
    ('GP', 'Guadeloupe', 'en', JSON_ARRAY('en'), TRUE, 'active', 1086),
    ('GQ', 'Equatorial Guinea', 'en', JSON_ARRAY('en'), TRUE, 'active', 1087),
    ('GR', 'Greece', 'en', JSON_ARRAY('en'), TRUE, 'active', 1088),
    ('GS', 'South Georgia and the South Sandwich Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1089),
    ('GT', 'Guatemala', 'en', JSON_ARRAY('en'), TRUE, 'active', 1090),
    ('GU', 'Guam', 'en', JSON_ARRAY('en'), TRUE, 'active', 1091),
    ('GW', 'Guinea-Bissau', 'en', JSON_ARRAY('en'), TRUE, 'active', 1092),
    ('GY', 'Guyana', 'en', JSON_ARRAY('en'), TRUE, 'active', 1093),
    ('HK', 'Hong Kong', 'en', JSON_ARRAY('en'), TRUE, 'active', 1094),
    ('HM', 'Heard Island and McDonald Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1095),
    ('HN', 'Honduras', 'en', JSON_ARRAY('en'), TRUE, 'active', 1096),
    ('HR', 'Croatia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1097),
    ('HT', 'Haiti', 'en', JSON_ARRAY('en'), TRUE, 'active', 1098),
    ('HU', 'Hungary', 'en', JSON_ARRAY('en'), TRUE, 'active', 1099),
    ('ID', 'Indonesia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1100),
    ('IE', 'Ireland', 'en', JSON_ARRAY('en'), TRUE, 'active', 1101),
    ('IL', 'Israel', 'en', JSON_ARRAY('en'), TRUE, 'active', 1102),
    ('IM', 'Isle of Man', 'en', JSON_ARRAY('en'), TRUE, 'active', 1103),
    ('IN', 'India', 'en', JSON_ARRAY('en'), TRUE, 'active', 1104),
    ('IO', 'British Indian Ocean Territory', 'en', JSON_ARRAY('en'), TRUE, 'active', 1105),
    ('IQ', 'Iraq', 'en', JSON_ARRAY('en'), TRUE, 'active', 1106),
    ('IR', 'Iran', 'en', JSON_ARRAY('en'), TRUE, 'active', 1107),
    ('IS', 'Iceland', 'en', JSON_ARRAY('en'), TRUE, 'active', 1108),
    ('IT', 'Italy', 'en', JSON_ARRAY('en'), TRUE, 'active', 1109),
    ('JE', 'Jersey', 'en', JSON_ARRAY('en'), TRUE, 'active', 1110),
    ('JM', 'Jamaica', 'en', JSON_ARRAY('en'), TRUE, 'active', 1111),
    ('JO', 'Jordan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1112),
    ('JP', 'Japan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1113),
    ('KE', 'Kenya', 'en', JSON_ARRAY('en'), TRUE, 'active', 1114),
    ('KG', 'Kyrgyzstan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1115),
    ('KH', 'Cambodia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1116),
    ('KI', 'Kiribati', 'en', JSON_ARRAY('en'), TRUE, 'active', 1117),
    ('KM', 'Comoros', 'en', JSON_ARRAY('en'), TRUE, 'active', 1118),
    ('KN', 'Saint Kitts and Nevis', 'en', JSON_ARRAY('en'), TRUE, 'active', 1119),
    ('KP', 'North Korea', 'en', JSON_ARRAY('en'), TRUE, 'active', 1120),
    ('KR', 'South Korea', 'en', JSON_ARRAY('en'), TRUE, 'active', 1121),
    ('KW', 'Kuwait', 'en', JSON_ARRAY('en'), TRUE, 'active', 1122),
    ('KY', 'Cayman Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1123),
    ('KZ', 'Kazakhstan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1124),
    ('LA', 'Laos', 'en', JSON_ARRAY('en'), TRUE, 'active', 1125),
    ('LB', 'Lebanon', 'en', JSON_ARRAY('en'), TRUE, 'active', 1126),
    ('LC', 'Saint Lucia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1127),
    ('LI', 'Liechtenstein', 'en', JSON_ARRAY('en'), TRUE, 'active', 1128),
    ('LK', 'Sri Lanka', 'en', JSON_ARRAY('en'), TRUE, 'active', 1129),
    ('LR', 'Liberia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1130),
    ('LS', 'Lesotho', 'en', JSON_ARRAY('en'), TRUE, 'active', 1131),
    ('LT', 'Lithuania', 'en', JSON_ARRAY('en'), TRUE, 'active', 1132),
    ('LU', 'Luxembourg', 'en', JSON_ARRAY('en'), TRUE, 'active', 1133),
    ('LV', 'Latvia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1134),
    ('LY', 'Libya', 'en', JSON_ARRAY('en'), TRUE, 'active', 1135),
    ('MA', 'Morocco', 'en', JSON_ARRAY('en'), TRUE, 'active', 1136),
    ('MC', 'Monaco', 'en', JSON_ARRAY('en'), TRUE, 'active', 1137),
    ('MD', 'Moldova', 'en', JSON_ARRAY('en'), TRUE, 'active', 1138),
    ('ME', 'Montenegro', 'en', JSON_ARRAY('en'), TRUE, 'active', 1139),
    ('MF', 'Saint Martin', 'en', JSON_ARRAY('en'), TRUE, 'active', 1140),
    ('MG', 'Madagascar', 'en', JSON_ARRAY('en'), TRUE, 'active', 1141),
    ('MH', 'Marshall Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1142),
    ('MK', 'North Macedonia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1143),
    ('ML', 'Mali', 'en', JSON_ARRAY('en'), TRUE, 'active', 1144),
    ('MM', 'Myanmar', 'en', JSON_ARRAY('en'), TRUE, 'active', 1145),
    ('MN', 'Mongolia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1146),
    ('MO', 'Macao', 'en', JSON_ARRAY('en'), TRUE, 'active', 1147),
    ('MP', 'Northern Mariana Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1148),
    ('MQ', 'Martinique', 'en', JSON_ARRAY('en'), TRUE, 'active', 1149),
    ('MR', 'Mauritania', 'en', JSON_ARRAY('en'), TRUE, 'active', 1150),
    ('MS', 'Montserrat', 'en', JSON_ARRAY('en'), TRUE, 'active', 1151),
    ('MT', 'Malta', 'en', JSON_ARRAY('en'), TRUE, 'active', 1152),
    ('MU', 'Mauritius', 'en', JSON_ARRAY('en'), TRUE, 'active', 1153),
    ('MV', 'Maldives', 'en', JSON_ARRAY('en'), TRUE, 'active', 1154),
    ('MW', 'Malawi', 'en', JSON_ARRAY('en'), TRUE, 'active', 1155),
    ('MX', 'Mexico', 'en', JSON_ARRAY('en'), TRUE, 'active', 1156),
    ('MY', 'Malaysia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1157),
    ('MZ', 'Mozambique', 'en', JSON_ARRAY('en'), TRUE, 'active', 1158),
    ('NA', 'Namibia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1159),
    ('NC', 'New Caledonia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1160),
    ('NE', 'Niger', 'en', JSON_ARRAY('en'), TRUE, 'active', 1161),
    ('NF', 'Norfolk Island', 'en', JSON_ARRAY('en'), TRUE, 'active', 1162),
    ('NG', 'Nigeria', 'en', JSON_ARRAY('en'), TRUE, 'active', 1163),
    ('NI', 'Nicaragua', 'en', JSON_ARRAY('en'), TRUE, 'active', 1164),
    ('NL', 'Netherlands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1165),
    ('NO', 'Norway', 'en', JSON_ARRAY('en'), TRUE, 'active', 1166),
    ('NP', 'Nepal', 'en', JSON_ARRAY('en'), TRUE, 'active', 1167),
    ('NR', 'Nauru', 'en', JSON_ARRAY('en'), TRUE, 'active', 1168),
    ('NU', 'Niue', 'en', JSON_ARRAY('en'), TRUE, 'active', 1169),
    ('NZ', 'New Zealand', 'en', JSON_ARRAY('en'), TRUE, 'active', 1170),
    ('OM', 'Oman', 'en', JSON_ARRAY('en'), TRUE, 'active', 1171),
    ('PA', 'Panama', 'en', JSON_ARRAY('en'), TRUE, 'active', 1172),
    ('PE', 'Peru', 'en', JSON_ARRAY('en'), TRUE, 'active', 1173),
    ('PF', 'French Polynesia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1174),
    ('PG', 'Papua New Guinea', 'en', JSON_ARRAY('en'), TRUE, 'active', 1175),
    ('PH', 'Philippines', 'en', JSON_ARRAY('en'), TRUE, 'active', 1176),
    ('PK', 'Pakistan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1177),
    ('PL', 'Poland', 'en', JSON_ARRAY('en'), TRUE, 'active', 1178),
    ('PM', 'Saint Pierre and Miquelon', 'en', JSON_ARRAY('en'), TRUE, 'active', 1179),
    ('PN', 'Pitcairn', 'en', JSON_ARRAY('en'), TRUE, 'active', 1180),
    ('PR', 'Puerto Rico', 'en', JSON_ARRAY('en'), TRUE, 'active', 1181),
    ('PS', 'Palestine', 'en', JSON_ARRAY('en'), TRUE, 'active', 1182),
    ('PT', 'Portugal', 'en', JSON_ARRAY('en'), TRUE, 'active', 1183),
    ('PW', 'Palau', 'en', JSON_ARRAY('en'), TRUE, 'active', 1184),
    ('PY', 'Paraguay', 'en', JSON_ARRAY('en'), TRUE, 'active', 1185),
    ('QA', 'Qatar', 'en', JSON_ARRAY('en'), TRUE, 'active', 1186),
    ('RE', 'Reunion', 'en', JSON_ARRAY('en'), TRUE, 'active', 1187),
    ('RO', 'Romania', 'en', JSON_ARRAY('en'), TRUE, 'active', 1188),
    ('RS', 'Serbia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1189),
    ('RU', 'Russia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1190),
    ('RW', 'Rwanda', 'en', JSON_ARRAY('en'), TRUE, 'active', 1191),
    ('SA', 'Saudi Arabia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1192),
    ('SB', 'Solomon Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1193),
    ('SC', 'Seychelles', 'en', JSON_ARRAY('en'), TRUE, 'active', 1194),
    ('SD', 'Sudan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1195),
    ('SE', 'Sweden', 'en', JSON_ARRAY('en'), TRUE, 'active', 1196),
    ('SG', 'Singapore', 'en', JSON_ARRAY('en'), TRUE, 'active', 1197),
    ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'en', JSON_ARRAY('en'), TRUE, 'active', 1198),
    ('SI', 'Slovenia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1199),
    ('SJ', 'Svalbard and Jan Mayen', 'en', JSON_ARRAY('en'), TRUE, 'active', 1200),
    ('SK', 'Slovakia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1201),
    ('SL', 'Sierra Leone', 'en', JSON_ARRAY('en'), TRUE, 'active', 1202),
    ('SM', 'San Marino', 'en', JSON_ARRAY('en'), TRUE, 'active', 1203),
    ('SN', 'Senegal', 'en', JSON_ARRAY('en'), TRUE, 'active', 1204),
    ('SO', 'Somalia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1205),
    ('SR', 'Suriname', 'en', JSON_ARRAY('en'), TRUE, 'active', 1206),
    ('SS', 'South Sudan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1207),
    ('ST', 'Sao Tome and Principe', 'en', JSON_ARRAY('en'), TRUE, 'active', 1208),
    ('SV', 'El Salvador', 'en', JSON_ARRAY('en'), TRUE, 'active', 1209),
    ('SX', 'Sint Maarten', 'en', JSON_ARRAY('en'), TRUE, 'active', 1210),
    ('SY', 'Syria', 'en', JSON_ARRAY('en'), TRUE, 'active', 1211),
    ('SZ', 'Eswatini', 'en', JSON_ARRAY('en'), TRUE, 'active', 1212),
    ('TC', 'Turks and Caicos Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1213),
    ('TD', 'Chad', 'en', JSON_ARRAY('en'), TRUE, 'active', 1214),
    ('TF', 'French Southern Territories', 'en', JSON_ARRAY('en'), TRUE, 'active', 1215),
    ('TG', 'Togo', 'en', JSON_ARRAY('en'), TRUE, 'active', 1216),
    ('TH', 'Thailand', 'en', JSON_ARRAY('en'), TRUE, 'active', 1217),
    ('TJ', 'Tajikistan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1218),
    ('TK', 'Tokelau', 'en', JSON_ARRAY('en'), TRUE, 'active', 1219),
    ('TL', 'Timor-Leste', 'en', JSON_ARRAY('en'), TRUE, 'active', 1220),
    ('TM', 'Turkmenistan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1221),
    ('TN', 'Tunisia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1222),
    ('TO', 'Tonga', 'en', JSON_ARRAY('en'), TRUE, 'active', 1223),
    ('TR', 'Turkey', 'en', JSON_ARRAY('en'), TRUE, 'active', 1224),
    ('TT', 'Trinidad and Tobago', 'en', JSON_ARRAY('en'), TRUE, 'active', 1225),
    ('TV', 'Tuvalu', 'en', JSON_ARRAY('en'), TRUE, 'active', 1226),
    ('TW', 'Taiwan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1227),
    ('TZ', 'Tanzania', 'en', JSON_ARRAY('en'), TRUE, 'active', 1228),
    ('UA', 'Ukraine', 'en', JSON_ARRAY('en'), TRUE, 'active', 1229),
    ('UG', 'Uganda', 'en', JSON_ARRAY('en'), TRUE, 'active', 1230),
    ('UM', 'United States Minor Outlying Islands', 'en', JSON_ARRAY('en'), TRUE, 'active', 1231),
    ('US', 'United States', 'en', JSON_ARRAY('en'), TRUE, 'active', 1232),
    ('UY', 'Uruguay', 'en', JSON_ARRAY('en'), TRUE, 'active', 1233),
    ('UZ', 'Uzbekistan', 'en', JSON_ARRAY('en'), TRUE, 'active', 1234),
    ('VA', 'Vatican City', 'en', JSON_ARRAY('en'), TRUE, 'active', 1235),
    ('VC', 'Saint Vincent and the Grenadines', 'en', JSON_ARRAY('en'), TRUE, 'active', 1236),
    ('VE', 'Venezuela', 'en', JSON_ARRAY('en'), TRUE, 'active', 1237),
    ('VG', 'Virgin Islands, British', 'en', JSON_ARRAY('en'), TRUE, 'active', 1238),
    ('VI', 'Virgin Islands, U.S.', 'en', JSON_ARRAY('en'), TRUE, 'active', 1239),
    ('VN', 'Vietnam', 'en', JSON_ARRAY('en'), TRUE, 'active', 1240),
    ('VU', 'Vanuatu', 'en', JSON_ARRAY('en'), TRUE, 'active', 1241),
    ('WF', 'Wallis and Futuna', 'en', JSON_ARRAY('en'), TRUE, 'active', 1242),
    ('WS', 'Samoa', 'en', JSON_ARRAY('en'), TRUE, 'active', 1243),
    ('YE', 'Yemen', 'en', JSON_ARRAY('en'), TRUE, 'active', 1244),
    ('YT', 'Mayotte', 'en', JSON_ARRAY('en'), TRUE, 'active', 1245),
    ('ZA', 'South Africa', 'en', JSON_ARRAY('en'), TRUE, 'active', 1246),
    ('ZM', 'Zambia', 'en', JSON_ARRAY('en'), TRUE, 'active', 1247),
    ('ZW', 'Zimbabwe', 'en', JSON_ARRAY('en'), TRUE, 'active', 1248);
