CREATE TABLE loan_products (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '贷款产品ID',
    loan_type VARCHAR(32) NOT NULL COMMENT '贷款类型：credit信用贷，collateralized抵押贷',
    asset_id BIGINT UNSIGNED NOT NULL COMMENT '放款资产ID',
    name VARCHAR(128) NOT NULL COMMENT '贷款产品名称',
    term_days INT UNSIGNED NOT NULL COMMENT '贷款期限天数',
    interest_rate DECIMAL(18,8) NOT NULL COMMENT '期限利率，0.02表示2%',
    interest_calculation_mode VARCHAR(32) NOT NULL DEFAULT 'full_term' COMMENT '提前还款计息方式：full_term完整周期，actual_days实际天数',
    min_kyc_level INT NOT NULL DEFAULT 0 COMMENT '最低KYC等级',
    min_amount DECIMAL(38,18) NOT NULL COMMENT '最小借款金额',
    max_amount DECIMAL(38,18) NULL COMMENT '最大借款金额，NULL表示无上限',
    status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '产品状态：active启用，disabled禁用',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    INDEX idx_loan_products_status (status),
    INDEX idx_loan_products_asset (asset_id),
    INDEX idx_loan_products_type_status (loan_type, status),
    CONSTRAINT fk_loan_products_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT chk_loan_products_type CHECK (loan_type IN ('credit', 'collateralized')),
    CONSTRAINT chk_loan_products_term CHECK (term_days > 0),
    CONSTRAINT chk_loan_products_interest_rate CHECK (interest_rate >= 0),
    CONSTRAINT chk_loan_products_interest_mode CHECK (interest_calculation_mode IN ('full_term', 'actual_days')),
    CONSTRAINT chk_loan_products_kyc CHECK (min_kyc_level >= 0),
    CONSTRAINT chk_loan_products_amount CHECK (min_amount > 0 AND (max_amount IS NULL OR max_amount >= min_amount)),
    CONSTRAINT chk_loan_products_status CHECK (status IN ('active', 'disabled'))
) COMMENT='用户贷款产品配置';

CREATE TABLE loan_orders (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '贷款订单ID',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '申请用户ID',
    product_id BIGINT UNSIGNED NOT NULL COMMENT '贷款产品ID',
    loan_type VARCHAR(32) NOT NULL COMMENT '订单贷款类型快照：credit信用贷，collateralized抵押贷',
    asset_id BIGINT UNSIGNED NOT NULL COMMENT '放款资产ID',
    amount DECIMAL(38,18) NOT NULL COMMENT '借款本金金额',
    interest_rate DECIMAL(18,8) NOT NULL COMMENT '订单利率快照',
    interest_calculation_mode VARCHAR(32) NOT NULL COMMENT '订单计息方式快照',
    term_days INT UNSIGNED NOT NULL COMMENT '订单期限天数快照',
    min_kyc_level INT NOT NULL DEFAULT 0 COMMENT '产品最低KYC等级快照',
    collateral_asset_id BIGINT UNSIGNED NULL COMMENT '抵押资产ID',
    collateral_amount DECIMAL(38,18) NULL COMMENT '抵押资产数量',
    status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '订单状态：pending待审核，disbursed已放款，rejected已拒绝，cancelled已取消，repaid已还款',
    idempotency_key VARCHAR(255) NOT NULL COMMENT '用户提交幂等键',
    interest_amount DECIMAL(38,18) NOT NULL DEFAULT 0 COMMENT '实际还款利息金额',
    repayment_amount DECIMAL(38,18) NOT NULL DEFAULT 0 COMMENT '实际还款总金额',
    approved_by BIGINT UNSIGNED NULL COMMENT '审核通过管理员ID',
    rejected_by BIGINT UNSIGNED NULL COMMENT '审核拒绝管理员ID',
    rejected_reason VARCHAR(255) NULL COMMENT '审核拒绝原因',
    approved_at TIMESTAMP(6) NULL COMMENT '审核通过时间',
    rejected_at TIMESTAMP(6) NULL COMMENT '审核拒绝时间',
    disbursed_at TIMESTAMP(6) NULL COMMENT '放款时间',
    due_at TIMESTAMP(6) NULL COMMENT '到期时间',
    cancelled_at TIMESTAMP(6) NULL COMMENT '取消时间',
    repaid_at TIMESTAMP(6) NULL COMMENT '还款时间',
    collateral_released_at TIMESTAMP(6) NULL COMMENT '抵押资产释放时间',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    UNIQUE KEY uq_loan_orders_user_idempotency (user_id, idempotency_key),
    INDEX idx_loan_orders_user_time (user_id, created_at),
    INDEX idx_loan_orders_product_status (product_id, status),
    INDEX idx_loan_orders_status_time (status, created_at),
    INDEX idx_loan_orders_asset_time (asset_id, created_at),
    CONSTRAINT fk_loan_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_loan_orders_product FOREIGN KEY (product_id) REFERENCES loan_products(id),
    CONSTRAINT fk_loan_orders_asset FOREIGN KEY (asset_id) REFERENCES assets(id),
    CONSTRAINT fk_loan_orders_collateral_asset FOREIGN KEY (collateral_asset_id) REFERENCES assets(id),
    CONSTRAINT fk_loan_orders_approved_by FOREIGN KEY (approved_by) REFERENCES admin_users(id),
    CONSTRAINT fk_loan_orders_rejected_by FOREIGN KEY (rejected_by) REFERENCES admin_users(id),
    CONSTRAINT chk_loan_orders_type CHECK (loan_type IN ('credit', 'collateralized')),
    CONSTRAINT chk_loan_orders_amount CHECK (amount > 0),
    CONSTRAINT chk_loan_orders_interest_rate CHECK (interest_rate >= 0),
    CONSTRAINT chk_loan_orders_interest_mode CHECK (interest_calculation_mode IN ('full_term', 'actual_days')),
    CONSTRAINT chk_loan_orders_term CHECK (term_days > 0),
    CONSTRAINT chk_loan_orders_kyc CHECK (min_kyc_level >= 0),
    CONSTRAINT chk_loan_orders_collateral_amount CHECK (collateral_amount IS NULL OR collateral_amount > 0),
    CONSTRAINT chk_loan_orders_status CHECK (status IN ('pending', 'disbursed', 'rejected', 'cancelled', 'repaid')),
    CONSTRAINT chk_loan_orders_repayment_amount CHECK (interest_amount >= 0 AND repayment_amount >= 0)
) COMMENT='用户贷款申请与订单';
