import type { Tag } from '@douyinfe/semi-ui';
import type { ComponentProps } from 'react';

type TagColor = NonNullable<ComponentProps<typeof Tag>['color']>;

type StatusMeta = {
  label: string;
  color: TagColor;
};

export const ADMIN_STATUS_META: Record<string, StatusMeta> = {
  attention: { label: '需要核查', color: 'orange' },
  balanced: { label: '对账平衡', color: 'green' },
  degraded: { label: '运行降级', color: 'orange' },
  healthy: { label: '健康', color: 'green' },
  not_configured: { label: '未配置', color: 'grey' },
  stale: { label: '行情已断流', color: 'red' },
  paused: { label: '暂停', color: 'orange' },
  stopped: { label: '已停止', color: 'grey' },
  running: { label: '运行中', color: 'light-blue' },
  live: { label: '实时运行', color: 'green' },
  open: { label: '进行中', color: 'light-blue' },
  filled: { label: '已成交', color: 'green' },
  expired: { label: '已过期', color: 'grey' },
  pending_confirmation: { label: '待确认', color: 'orange' },
  confirmed: { label: '已确认', color: 'green' },
  invalid: { label: '已作废', color: 'grey' },
  hidden: { label: '隐藏', color: 'grey' },
  processing: { label: '处理中', color: 'light-blue' },
  assigned: { label: '已分配', color: 'light-blue' },
  available: { label: '可用', color: 'green' },
  released: { label: '已释放', color: 'green' },
  partially_released: { label: '部分释放', color: 'light-blue' },
  repaid: { label: '已还款', color: 'green' },
  overdue: { label: '已逾期', color: 'red' },
  active: { label: '启用', color: 'green' },
  allocated: { label: '已获配', color: 'green' },
  partial_allocated: { label: '已部分派发', color: 'light-blue' },
  refunded: { label: '已退款', color: 'grey' },
  allow: { label: '放行', color: 'green' },
  approved: { label: '已通过', color: 'green' },
  archived: { label: '已归档', color: 'grey' },
  cancelled: { label: '已取消', color: 'grey' },
  canceled: { label: '已取消', color: 'grey' },
  closed: { label: '已平仓', color: 'green' },
  completed: { label: '已完成', color: 'green' },
  deny: { label: '拒绝', color: 'red' },
  disabled: { label: '禁用', color: 'grey' },
  distribution: { label: '派发中', color: 'light-blue' },
  draft: { label: '草稿', color: 'grey' },
  down: { label: '看跌', color: 'red' },
  enabled: { label: '启用', color: 'green' },
  failed: { label: '失败', color: 'red' },
  inactive: { label: '禁用', color: 'grey' },
  liquidated: { label: '已强平', color: 'red' },
  listed: { label: '已上市', color: 'green' },
  locked: { label: '锁定', color: 'orange' },
  long: { label: '做多', color: 'green' },
  loss: { label: '亏损', color: 'red' },
  manual_review: { label: '人工复核', color: 'orange' },
  not_required: { label: '无需支付', color: 'grey' },
  opened: { label: '持仓中', color: 'light-blue' },
  paid: { label: '已支付', color: 'green' },
  partially_filled: { label: '部分成交', color: 'light-blue' },
  pending: { label: '待处理', color: 'orange' },
  preheat: { label: '预热中', color: 'orange' },
  published: { label: '已发布', color: 'green' },
  needs_reload: { label: '待重载', color: 'orange' },
  redeemed: { label: '已赎回', color: 'green' },
  rejected: { label: '已拒绝', color: 'red' },
  review: { label: '人工复核', color: 'orange' },
  settled: { label: '已结算', color: 'green' },
  short: { label: '做空', color: 'red' },
  skipped: { label: '已跳过', color: 'grey' },
  subscribed: { label: '已申购', color: 'light-blue' },
  subscription: { label: '申购中', color: 'light-blue' },
  success: { label: '成功', color: 'green' },
  suspended: { label: '暂停', color: 'orange' },
  unpaid: { label: '未支付', color: 'orange' },
  up: { label: '看涨', color: 'green' },
  win: { label: '盈利', color: 'green' },
  true: { label: '启用', color: 'green' },
  false: { label: '禁用', color: 'grey' }
};
